-- Phlebotomist onboarding / employment contracts (from legacy wp_phleb_contracts).
-- Linked to phlebotomy_applications.id via phleb_id.
CREATE TABLE IF NOT EXISTS npn_phleb_contracts (
  id bigint NOT NULL AUTO_INCREMENT,
  phleb_id int NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status enum('draft','submitted','approved','rejected') NOT NULL DEFAULT 'submitted',
  contractor_name varchar(255) DEFAULT NULL,
  address text,
  phone varchar(64) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  full_name varchar(255) DEFAULT NULL,
  dob varchar(64) DEFAULT NULL,
  home_address text,
  mobile_number varchar(64) DEFAULT NULL,
  personal_email varchar(255) DEFAULT NULL,
  emergency_contact text,
  areas_covered text,
  travel_radius varchar(64) DEFAULT NULL,
  available_days text,
  weekend_availability varchar(64) DEFAULT NULL,
  clinic_mobile varchar(64) DEFAULT NULL,
  own_vehicle varchar(16) DEFAULT NULL,
  account_name varchar(255) DEFAULT NULL,
  sort_code varchar(32) DEFAULT NULL,
  account_number varchar(64) DEFAULT NULL,
  payment_frequency varchar(64) DEFAULT NULL,
  cv_file varchar(512) DEFAULT NULL,
  phlebotomy_qualifications text,
  relevant_certificates text,
  cpd_training text,
  clinical_competencies text,
  hep_b_proof varchar(512) DEFAULT NULL,
  occupational_health_records varchar(512) DEFAULT NULL,
  dbs_adults varchar(512) DEFAULT NULL,
  dbs_children varchar(512) DEFAULT NULL,
  right_to_work varchar(512) DEFAULT NULL,
  utr_file varchar(512) DEFAULT NULL,
  contractor_signature text,
  contractor_signature_date varchar(64) DEFAULT NULL,
  youth_signature text,
  youth_signature_date varchar(64) DEFAULT NULL,
  declaration_signature text,
  declaration_name varchar(255) DEFAULT NULL,
  declaration_date varchar(64) DEFAULT NULL,
  bank_signature text,
  bank_signature_date varchar(64) DEFAULT NULL,
  reviewed_by varchar(150) DEFAULT NULL,
  reviewed_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_phleb_id (phleb_id),
  KEY idx_status (status),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
