-- Insert dummy phlebotomist for testing
INSERT INTO phlebotomy_applications (
    full_name,
    home_address,
    phone,
    email,
    employment_type,
    working_hours,
    other_job,
    unavailable_times,
    drive,
    travel_radius,
    dbs,
    certifications,
    experience,
    exp_years,
    services,
    first_aid,
    first_aid_desc,
    trainer,
    trainer_desc,
    training_academy,
    payment_terms,
    extra_info,
    lat,
    lng,
    created_at,
    is_active,
    is_email_sent
) VALUES (
    'Hafiz Test User',
    '123 Test Street, London, UK',
    '+44 7123 456789',
    'hafizg346@gmail.com',
    'Full-time',
    '9:00 AM - 5:00 PM',
    'No',
    'Weekends',
    'Yes',
    '50 miles',
    'Yes',
    'Phlebotomy Certificate, CPR Certified',
    'Hospital phlebotomy, mobile blood collection',
    '3 years',
    'Blood collection, specimen handling, patient care',
    'Yes',
    'CPR and First Aid certified through Red Cross',
    'Yes',
    'Trained new phlebotomists at previous hospital',
    'London Medical Training Academy',
    'Bank transfer, weekly payments',
    'Available for emergency calls, flexible schedule',
    '51.5074',
    '-0.1278',
    NOW(),
    1,
    0
);
